#!/usr/bin/env python3
"""Write a human-readable phase document from session state.

Creates clean markdown files in {output_dir}/docs/ that can be loaded at the
start of the next phase instead of relying on conversation history.

Usage:
  python write_phase_doc.py --id PROJECT_ID --phase requirements
  python write_phase_doc.py --id PROJECT_ID --phase architecture
  python write_phase_doc.py --id PROJECT_ID --phase backlog
"""
import argparse
import json
from pathlib import Path

PHASES = ("requirements", "architecture", "backlog")


def write_requirements(session: dict, docs_dir: Path) -> Path:
    req = session.get("requirements", {})
    lines = [
        f"# Requirements: {session['name']}",
        "",
        f"> Generated by ForgeStack | Project ID: `{session['id']}`",
        "",
        "## Features",
        "",
    ]
    for f in req.get("features", []):
        lines.append(f"- {f}")
    lines += ["", "## Constraints", ""]
    for c in req.get("constraints", []):
        lines.append(f"- {c}")
    lines += [
        "",
        "## Properties",
        "",
        "| Property | Value |",
        "|----------|-------|",
        f"| Scale | {req.get('scaling', 'not set')} |",
        f"| Auth required | {req.get('auth_required', 'not set')} |",
        f"| Auth type | {req.get('auth_type', 'not set')} |",
        f"| Preferred stack | {req.get('preferred_stack') or 'no preference'} |",
    ]
    out = docs_dir / "requirements.md"
    out.write_text("\n".join(lines))
    return out


def write_architecture(session: dict, docs_dir: Path) -> Path:
    stack = session.get("tech_stack", {})
    lines = [
        f"# Architecture: {session['name']}",
        "",
        f"> Generated by ForgeStack | Project ID: `{session['id']}`",
        "",
        "## Technology Stack",
        "",
        "| Layer | Choice | Rationale |",
        "|-------|--------|-----------|",
    ]
    rationale = stack.get("rationale", {})
    for layer in ("language", "backend", "frontend", "database", "auth", "infrastructure"):
        val = stack.get(layer, "—")
        reason = rationale.get(layer, "—")
        lines.append(f"| {layer.title()} | {val} | {reason} |")
    diagrams = session.get("diagrams", {})
    if diagrams:
        lines += ["", "## Diagrams", ""]
        for name, path in diagrams.items():
            lines.append(f"- [{name}]({path})")
    out = docs_dir / "architecture.md"
    out.write_text("\n".join(lines))
    return out


def write_backlog(session: dict, docs_dir: Path) -> Path:
    backlog = session.get("backlog", [])
    total_sp = sum(t.get("story_points", 0) for t in backlog)
    lines = [
        f"# Backlog: {session['name']}",
        "",
        f"> Generated by ForgeStack | Project ID: `{session['id']}`",
        f"> {len(backlog)} tasks | {total_sp} story points",
        "",
        "| # | ID | Title | Layer | SP | Spec Refs | Status |",
        "|---|-----|-------|-------|----|-----------|--------|",
    ]
    for i, t in enumerate(backlog, 1):
        refs = ", ".join(t.get("spec_refs", []))
        lines.append(
            f"| {i} | {t.get('id')} | {t.get('title')} | "
            f"{t.get('layer')} | {t.get('story_points')} | {refs} | {t.get('status')} |"
        )
    lines += ["", "---", "", "## Task Details", ""]
    for t in backlog:
        refs_str = ", ".join(t.get("spec_refs", [])) or "none"
        deps_str = ", ".join(t.get("dependencies", [])) or "none"
        lines += [
            f"### [{t.get('id')}] {t.get('title')}",
            "",
            f"**Layer**: {t.get('layer')} | **Points**: {t.get('story_points')} | **Status**: {t.get('status')}",
            f"**Spec Refs**: {refs_str}",
            f"**Depends on**: {deps_str}",
            f"**Test**: `{t.get('test_command', '—')}`",
            "",
            t.get("description", ""),
            "",
            "**Acceptance Criteria**:",
            "",
        ]
        for ac in t.get("acceptance_criteria", []):
            lines.append(f"- [ ] {ac}")
        lines.append("")
    out = docs_dir / "backlog.md"
    out.write_text("\n".join(lines))
    return out


WRITERS = {
    "requirements": write_requirements,
    "architecture": write_architecture,
    "backlog": write_backlog,
}


def main():
    parser = argparse.ArgumentParser(description="Write a ForgeStack phase document.")
    parser.add_argument("--id", required=True, help="Project ID")
    parser.add_argument("--phase", required=True, choices=PHASES, help="Phase to export")
    args = parser.parse_args()

    session_path = Path(f".forgestack/sessions/{args.id}.json")
    if not session_path.exists():
        print(f"Error: session '{args.id}' not found at {session_path}", flush=True)
        raise SystemExit(1)

    session = json.loads(session_path.read_text())
    docs_dir = Path(session.get("output_dir", f"output/{args.id}")) / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    out_path = WRITERS[args.phase](session, docs_dir)
    print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
